# Generated by Django 4.1.7 on 2023-03-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
    ]
