# Generated by Django 4.1.2 on 2023-03-23 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0003_juegopopular_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='juegoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJuego', models.CharField(max_length=50)),
                ('desarrollador', models.CharField(max_length=50)),
                ('estreno', models.CharField(max_length=50)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
